### ISSUE TITLE
Doppelter Menülink "Beiträge"

### ISSUE THREAD

**Issue by rattermeyer** [opitzconsulting/opitzconsulting.github.io#13]
Aktuell sehe ich in der Kopfzeile "Beiträge" "Beiträge".

**Comment by codescape** [comment]
Oh... die Pagination hat sich gemeldet... sollten wir eh statisch rendern und nicht die Dynamik der aktuellen Lösung verfolgen.

**Comment by marcobuss** [comment]
Kann ich bestätigen. Scheint die 2. Seite der Beiträge zu sein.

**Comment by codescape** [comment]
Siehe hier: https://github.com/opitzconsulting/opitzconsulting.github.io/blob/master/_includes/header.html#L17

**Comment by codescape** [comment]
solved and closed with 4df4495
